apiVersion: v1
kind: ServiceAccount
metadata:
  name: modelium-executor
  namespace: modelium
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: modelium-executor-role
  namespace: modelium
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log"]
    verbs: ["get", "list", "watch", "create", "delete"]
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: modelium-executor-rolebinding
  namespace: modelium
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: modelium-executor-role
subjects:
  - kind: ServiceAccount
    name: modelium-executor
    namespace: modelium
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: modelium-deployment
  namespace: modelium
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: modelium-deployment-role
rules:
  - apiGroups: ["serving.kserve.io"]
    resources: ["inferenceservices"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["services", "configmaps"]
    verbs: ["get", "list", "watch", "create", "update", "patch"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: modelium-deployment-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: modelium-deployment-role
subjects:
  - kind: ServiceAccount
    name: modelium-deployment
    namespace: modelium

