apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "modelium.fullname" . }}-config
  labels:
    {{- include "modelium.labels" . | nindent 4 }}
data:
  modelium.yaml: |
    {{- toYaml .Values.config | nindent 4 }}

