{{- if .Values.persistence.models.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "modelium.fullname" . }}-models
  labels:
    {{- include "modelium.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.models.accessMode }}
  storageClassName: {{ .Values.persistence.models.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.models.size }}
{{- end }}
---
{{- if .Values.persistence.logs.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "modelium.fullname" . }}-logs
  labels:
    {{- include "modelium.labels" . | nindent 4 }}
spec:
  accessModes:
    - {{ .Values.persistence.logs.accessMode }}
  storageClassName: {{ .Values.persistence.logs.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.logs.size }}
{{- end }}

